#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail

fact_table="opt/data/facts/tables"

if [ -z "${1-}" ]
then
  echo "Usage: $(basename "${0-}") <path to json results file>"
  exit 1
fi

jq -er '
   (@text "\(length) pull requests matched your search."),

   (map(decant("repository")[][]) | unique | @text "\(length) repositories matched."),

   (map(decant("resourcePath")[]) | unique | @text "\(length) authors merged a pull request."),

   (map(decant("commits")[][]) | @text "\(add) total commits."),

   (map(decant("changedFiles")[]) | @text "\(add) total files touched."),

   (map(pluck("title")[][]) | join(" ") | split(" ") | length |  @text "\(.) tokens in pull request titles."),

   (map(pluck("title")[][]) | join(" ") | split(" ") | unique | length |  @text "\(.) unique tokens.")
' "$1" \
    | perl -lwpe 's{\s}{\t}' \
    | column -ts $'\t'

mkdir -p $fact_table

(jq -ner '@text "Count\tRepository"'; jq -er 'map(decant("repository")[][])[]' "$1" \
     | sort -iV | uniq -c | sort -rn | spaces2tsv) \
    > "$fact_table/pull_requests_by_repository.tsv"

(jq -ner '@text "Count\tRepository"'; jq -er 'map(decant("repository")[][])[]' "$1" \
     | sort -iV | uniq -c | sort -rn | spaces2tsv) \
    > "$fact_table/pull_requests_by_repository.tsv"

echo
echo "Top Repos By Pull Requests:"
head -n6 "$fact_table/pull_requests_by_repository.tsv"
